#!/bin/bash
#SBATCH --time=72:00:00
#SBATCH --job-name=blazor
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=22
#SBATCH --mem=64gb
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ashutiwa@iu.edu

srun python data_loader.py
